name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run backend tests
        run: pytest -q

  frontend-build:
    runs-on: ubuntu-latest
    needs: backend-test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install & Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: frontend-build
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build backend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/luma-backend:latest -f backend/Dockerfile .
          docker push ghcr.io/${{ github.repository_owner }}/luma-backend:latest

      - name: Build frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/luma-frontend:latest -f frontend/Dockerfile .
          docker push ghcr.io/${{ github.repository_owner }}/luma-frontend:latest
# Note: Replace YOUR_GH_USERNAME with your actual GitHub username in the backend image path in deployment/docker-compose.yml.
